### PR TITLE
add i3 config

### PR DESCRIPTION
**Pull request by stapelberg**

### CODE REVIEW

**Comment by stapelberg** [comment]
You might want to hold off merging this one until I confirm that commits are actually announced properly :)

**Comment by mvdan** [comment]
Any progress, @stapelberg?

**Comment by stapelberg** [comment]
We’ve had a commit in the meantime, but it wasn’t announced. I think this is because the bot doesn’t identify itself to the IRC services and #i3 requires users to be registered. I’ll try to take a look at fixing that later today.

**Comment by stapelberg** [comment]
Sorry for the delay.

I can confirm that the PR is correct and works for #i3 as soon as one adds `"pass": "<account>:<password>"` to the config after registering the nickname with FreeNode services.

I think this is ready to merge :)

**Comment by mvdan** [comment]
Awesome, thanks!

**Pull request merged**
