### PR TITLE
update to latest go-gitlab

### PR DESCRIPTION
**Pull request by stapelberg**

### CODE REVIEW

**Comment by mvdan** [comment]
I haven't used nor maintained this software in years; do you want it? Happy to transfer the repository elsewhere, like your account. Happy to approve/merge this one, but it doesn't really make sense to continue that way :)

**Comment by stapelberg** [comment]
Yeah, we can transfer it to stapelberg/gibot. I’m still using it currently :)

**Comment by mvdan** [comment]
> stapelberg/gibot already exists 

oops. I guess you need to rename your fork first?

**Comment by stapelberg** [comment]
Deleted my fork

**Comment by mvdan** [comment]
Request sent :) Over to you!

**Comment by stapelberg** [comment]
Thanks!

**Comment by mvdan** [comment]
I assume you'll want to alter the import path and the "sponsor" info, as well as any other references/links to my username or domain :) Just FYI.

**Comment by stapelberg** [comment]
The old import path still works, so I think I’ll leave it as-is for now if you don’t mind. Not sure if there are any other users than me :)

**Comment by mvdan** [comment]
:+1: the page on the domain doesn't cost me anything so I'll leave it up for the foreseeable future.

**Pull request closed without merging**
