### PR TITLE
when posting n messages, do 1 join/part instead of n

### PR DESCRIPTION
**Pull request by stapelberg**

### CODE REVIEW

**Comment by stapelberg** [comment]
The travis failure looks unrelated to me (gitlab client version skew, it seems?)

**Comment by mvdan** [comment]
Ah, yes, because on 1.10 we can't easily download the right versions of the dependencies.

I'd rather not vendor, so I'll bump the minimum version to 1.11 instead. 1.12 is around the corner anyway, so 1.10 was about to be dropped soon in any case.

**Review by mvdan — APPROVED** [review]
Please rebase on master to fix CI.

Also, these little changes make me a bit uneasy with no tests :) I hope you're testing manually. I guess I can keep running older master versions temporarily if anything breaks for my use case.

**Comment by mvdan** [comment]
To clarify - when I said "no tests", I meant my naive former self for not writing any, not you for not adding any. I don't think it's fair to demand tests from PRs when the repo itself has zero.

I wonder how one would write good, reliable tests with IRC. Perhaps spinning up real or fake IRC servers, kinda like httptest. I never bothered to do that since I thought noone else would use this software.

**Comment by stapelberg** [comment]
> Please rebase on master to fix CI.

Done.

> Also, these little changes make me a bit uneasy with no tests :) I hope you're testing manually. I guess I can keep running older master versions temporarily if anything breaks for my use case.

I am testing manually indeed :)

> I wonder how one would write good, reliable tests with IRC. Perhaps spinning up real or fake IRC servers, kinda like httptest. I never bothered to do that since I thought noone else would use this software.

In RobustIRC, we just input/output IRC messages. The most involved is certainly the session establishment, which you can find at https://github.com/robustirc/robustirc/blob/38fd78c7f0b39fe25a78d33805b89b26617363c3/internal/ircserver/ircserver_test.go#L87. Individual features are easier, see e.g. https://github.com/robustirc/robustirc/blob/38fd78c7f0b39fe25a78d33805b89b26617363c3/internal/ircserver/cmd_away_test.go

**Comment by mvdan** [comment]
Thanks!

**Pull request merged**
